### ISSUE TITLE
[feat] PENALTY 프로토콜 기능 구현 요청

### ISSUE THREAD

**Issue by sunwchoi** [suhwan22/ft_transcendence_backend#70]
1. PENALTY
지금은 notice 문자열 형식으로 닷지 페널티를 알려줌
PENALYT라는 프로토콜이 따로 필요, {min: number, sec:number} 같이 남은 시간을 숫자로 알려줘야함
2. 최근 전적조회
-> 최근 rate만 줘도 됨, userId 없는 버전 필요
3. END
기존 버전으로(isLeft로 승자를 알려주는 버전) 갈거임
main에 고친 버전이 올라와있는지 모르겠는데 end 프로토콜을 보내야할때 서버가 다운됨
에러메세지 -------
nestapp  | /app/dist/sockets/game/games-socket.service.js:321
nestapp  |         win = winner.data.player.player;
nestapp  |                           ^
nestapp  |
nestapp  | TypeError: Cannot read properties of undefined (reading 'player')
nestapp  |     at GamesSocketService.endGameWithExtra (/app/dist/sockets/game/games-socket.service.js:321:27)
nestapp  |     at GamesSocketService.checkTimePause (/app/dist/sockets/game/games-socket.service.js:289:18)
nestapp  |     at Timeout.<anonymous> (/app/dist/sockets/game/games-socket.service.js:273:51)
nestapp  |     at listOnTimeout (node:internal/timers:559:17)
nestapp  |     at processTimers (node:internal/timers:502:7)
nestapp exited with code 1
---------- 
4. JOIN_GAME
프로토콜 자체가 사라짐..? 왜지?

**Comment by wkdtpgns5016** [comment]
1. YES
2. 단순 레이팅 점수 조회라면 uesrs/game-records/:id 로 조회가능함, 나중에 users/game-records/me로 바꿀 예정 (docs 참조)
3. 현재 main 브랜치는 수정한 END 임, 기존껄로 교체하겠음
4. 현재 서버는 클라이언트에서 JOIN 프로토콜로 메시지를 받음 => JOIN_GAME 으로 수정
